import mysql.connector
from dotenv import load_dotenv
import os

load_dotenv()

# Database connection and insertion functions
def get_connection():
    return mysql.connector.connect(
        host=os.getenv("MYSQL_HOST"),
        user=os.getenv("MYSQL_USER"),
        password=os.getenv("MYSQL_PASSWORD"),
        database=os.getenv("MYSQL_DATABASE")
    )

# Insert a transaction into the transactions table
def insert_transaction(transaction):

    # Open a connection to MySQL.
    connection = get_connection()
    cursor = connection.cursor()

    # Insert the transaction into the transactions table.
    query = """
    INSERT INTO transactions (
        transaction_time,
        amount,
        v1, v2, v3, v4, v5, v6, v7,
        v8, v9, v10, v11, v12, v13, v14,
        v15, v16, v17, v18, v19, v20, v21,
        v22, v23, v24, v25, v26, v27, v28
    )
    VALUES (
        %s, %s,
        %s, %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s, %s, %s
    )
    """

    values = (
        transaction["Time"],
        transaction["Amount"],
        transaction["V1"],
        transaction["V2"],
        transaction["V3"],
        transaction["V4"],
        transaction["V5"],
        transaction["V6"],
        transaction["V7"],
        transaction["V8"],
        transaction["V9"],
        transaction["V10"],
        transaction["V11"],
        transaction["V12"],
        transaction["V13"],
        transaction["V14"],
        transaction["V15"],
        transaction["V16"],
        transaction["V17"],
        transaction["V18"],
        transaction["V19"],
        transaction["V20"],
        transaction["V21"],
        transaction["V22"],
        transaction["V23"],
        transaction["V24"],
        transaction["V25"],
        transaction["V26"],
        transaction["V27"],
        transaction["V28"]
    )

    # Execute the query and commit the transaction.
    cursor.execute(query, values)
    connection.commit()

    # Get the ID generated by AUTO_INCREMENT.
    transaction_id = cursor.lastrowid

    # Close the cursor and connection to free up resources.
    cursor.close()
    connection.close()

    return transaction_id

# Insert a prediction into the predictions table
def insert_prediction(
    transaction_id,
    fraud_probability,
    risk_level,
    model_version
):
    connection = get_connection()
    cursor = connection.cursor()

    query = """
    INSERT INTO predictions (
        transaction_id,
        fraud_probability,
        risk_level,
        model_version
    )
    VALUES (%s, %s, %s, %s)
    """

    values = (
        transaction_id,
        fraud_probability,
        risk_level,
        model_version
    )

    cursor.execute(query, values)
    connection.commit()

    prediction_id = cursor.lastrowid

    cursor.close()
    connection.close()

    return prediction_id

def insert_investigation(
    transaction_id,
    status,
    analyst_decision=None,
    analyst_notes=None
):

    connection = get_connection()
    cursor = connection.cursor()

    query = """
    INSERT INTO investigations (
        transaction_id,
        status,
        analyst_decision,
        analyst_notes
    )
    VALUES (%s, %s, %s, %s)
    """

    values = (
        transaction_id,
        status,
        analyst_decision,
        analyst_notes
    )

    cursor.execute(query, values)
    connection.commit()

    investigation_id = cursor.lastrowid

    cursor.close()
    connection.close()

    return investigation_id

def insert_audit_log(
    transaction_id,
    action,
    details=None
):

    connection = get_connection()
    cursor = connection.cursor()

    query = """
    INSERT INTO audit_logs (
        transaction_id,
        action,
        details
    )
    VALUES (%s, %s, %s)
    """

    values = (
        transaction_id,
        action,
        details
    )

    cursor.execute(query, values)
    connection.commit()

    log_id = cursor.lastrowid

    cursor.close()
    connection.close()

    return log_id

# Update an investigation with the analyst's final decision and optional notes.
def update_investigation_decision(
    investigation_id,
    analyst_decision,
    analyst_notes=None
):
    connection = get_connection()
    cursor = connection.cursor()

    query = """
    UPDATE investigations
    SET
        status = %s,
        analyst_decision = %s,
        analyst_notes = %s
    WHERE investigation_id = %s
    """

    values = (
        "CLOSED",
        analyst_decision,
        analyst_notes,
        investigation_id
    )

    cursor.execute(query, values)
    connection.commit()

    cursor.close()
    connection.close()

    return cursor.rowcount

# Check whether a transaction exists in the database.
def transaction_exists(transaction_id):

    connection = get_connection()
    cursor = connection.cursor()

    query = """
    SELECT transaction_id
    FROM transactions
    WHERE transaction_id = %s
    """

    # Execute the query with the provided transaction_id.
    cursor.execute(query, (transaction_id,))

    # Get the first matching row, if one exists.
    result = cursor.fetchone()

    cursor.close()
    connection.close()

    # Return True if the transaction was found.
    return result is not None

# Find the transaction associated with an investigation.
def get_transaction_id_for_investigation(investigation_id):

    connection = get_connection()
    cursor = connection.cursor()

    query = """
    SELECT transaction_id
    FROM investigations
    WHERE investigation_id = %s
    """

    cursor.execute(query, (investigation_id,))

    # Get the matching row, if it exists.
    result = cursor.fetchone()

    cursor.close()
    connection.close()

    # Return the transaction ID, or None if not found.
    if result is None: return None

    return result[0]